services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.client
    image: driveway-frontend
    ports:
      - "3000:3000"
    env_file:
      - ./apps/client/.env
    environment:
      - NODE_ENV=production
    depends_on:
      backend:
        condition: service_started
    networks:
      - mynetwork

  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.api
    image: driveway-backend
    ports:
      - "3001:3001"
    env_file:
      - ./apps/api/.env
    environment:
      - NODE_ENV=production
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
